### ISSUE TITLE
Integrate docs in MyNode to enable user to read it locally

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode_docs#1]
**Is your content request related to a problem? Please describe.**
Instead of just hosting the documentation on a public website, the documentation should be include in the MyNode package to enable users in learning and troubleshooting the installed apps.

**Describe the solution you'd like**
- [ ] Host the complete website on a /docs route
- [ ] Link relevant articles inside every app
- [ ] Link relevant articles beside the known error messages (maybe for later)

**Additional context**
Hosting it locally on every mynode device will also help reduce the load on the public website and avoid the single point of failure.

This idea was originally suggested by "M D" on our private Telegram group.

**Comment by davterra** [comment]
Sorry to say I just saw this. I'm curious as to the security implications of a group of us, mostly unknown to Taylor and each other, having the ability to push content that ends up inside of users actual mynode device?
I assume we would have some PR review but my first thought is that it would be easy to include a malicious link or keylogger in such a situation if not closely reviewed.
