### ISSUE TITLE
"Getting started" section

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode_docs#14]
**Is your content request related to a problem? Please describe.**
How to setup mynode? What to expect?

**Describe the solution you'd like**
- [ ] Hardware options and recommendations
- [ ] Flashing the card
- [ ] Using existing blockchain
- [ ] Converting Casa, RaspiBlitz, etc
- [ ] Wait time for IBD vs Quicksync
- [ ] Troubleshooting

**Additional context**
Instructions from the main website can be the baseline. Add screenshots for each step assuming the user has no prior experience with Linux. List all the available videos and articles on the internet.

**Comment by keblek** [comment]
I cant self assign here but I will take this one
