### ISSUE TITLE
Lightning section

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode_docs#3]
**Is your content request related to a problem? Please describe.**
All articles related to LND should be part of the Lightning section

**Describe the solution you'd like**
- [ ] Overview
- [ ] Setup
- [x] LND Connect
- [ ] LND Hub
- [ ] RTL
- [x] Thunderhub
- [ ] LNbits
- [ ] Connecting external mobile/desktop apps
- [ ] Troubleshooting

**Additional context**
It should be one stop shop for all things lightning related.

**Comment by jason-me** [comment]
Request a page/short article with instructions on finding the initial credentials for Lightning Terminal login under the lightning "Wallet" button > Show Password.

**Comment by tehelsper** [comment]
Added.

https://mynodebtc.github.io/lightning/lightning-terminal.html

**Comment by jason-me** [comment]
Beautiful!
