### ISSUE TITLE
Problem "Using Data from Existing Node" as documented

### ISSUE THREAD

**Issue by StevenBlack** [mynodebtc/mynode_docs#36]
**Describe the bug**

I'm having a problem "[Using Data from Existing Node](https://github.com/mynodebtc/mynode_docs/blob/master/docs/device/existing-node.md)" and I'd like to update the docs with the solution, once I find one.

**My Steps**
I issue this command
```
$ sudo scp -r admin@mynode.local:/mnt/hdd/mynode/bitcoin/blocks /Volumes/myfolder/
admin@mynode.local's password:  xxxx
```
And the following is returned.  **Take Note**: my issue is with `Permission denied`, not the other thing.
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
scp: /mnt/hdd/mynode/bitcoin/blocks: Permission denied
```

**Expected behavior**

I would expect that using `scp` — as documented — to copy data should just work.  

**Things I've tried**

* I tried adding user `admin` to the `group` named `bitcoin` before trying again. No effect.
* I tried `sudo systemctl stop bitcoind` and `sudo systemctl stop lnd` on the source myNode before trying again. No effect.

**Question**

Any insight to share on why I would receive `Permission denied` here?  I'll amend the docs once we know why.

**Comment by StevenBlack** [comment]
Any insight on this?  I kinda need to get 678k blocks copied over, from a full-bird oem myNode, and the docs appear to be incomplete and/or misleading as to what it will take to do that.

**Comment by StevenBlack** [comment]
**Interesting to note**: on my umbrel node, this just works, no `Permission denied` issues at all.

With Umbrel, the interactive ssh user is `umbrel` and the `umbrel` user or group owns the `bitcoin/` folders.

With myNode, the interactive ssh user is `admin` and, by default, `admin` is not a member of the `bitcoin` group that owns the `bitcoin/` folders.

So this is either a permissions bug, or a documentation bug, in myNode.

This new node is going to be an Umbrel node now, so no rush acking or answering this guys I'm good.

**Comment by tehelsper** [comment]
It's easier to push than to pull since the bitcoin user does not have a password. For example, this would be easier:

sudo scp <folder>/blocks myuser@external_node:/path/to/folder

Otherwise, you could temporarily change the permissions but that is a bit messier.

**Comment by StevenBlack** [comment]
Taylor @tehelsper how do you want it to work?  Is the doc the spec, or change the docs to reflect how it presently works?  

Actually it presently doesn't work since the `admin` user is powerless here, by default.

Scrub "[Using Data from Existing Node](https://github.com/mynodebtc/mynode_docs/blob/master/docs/device/existing-node.md)" from the docs? How do you want to play it?

**Comment by tehelsper** [comment]
Yeah, I added some steps that would help. I didn't test a fully copy though.

**Comment by StevenBlack** [comment]
Awesome Taylor @tehelsper.  Looks good!

**Comment by StevenBlack** [comment]
By the way Taylor, I think the `chmod -R 744` thing should grant the whole `/mynode` space to the `admin` user, not just the `/mnt/hdd/mynode/bitcoin` folders.

How is that not a sensible default for the `admin` user?

```
# Make sure the whole mynode space is readable by the admin user
sudo chmod -R 744 /mnt/hdd/mynode
```

**Comment by StevenBlack** [comment]
Taylor @tehelsper I'm actually only getting around to this now. 🤭

With an OEM myNode, here is what I get.  Still `Permission denied`.

Is there something with your rig that's different from what was shipped earlier this year?  My guess: Mos Def.

```
$ sudo chmod -R 744 /mnt/hdd/mynode/bitcoin/blocks
[sudo] password for admin:

admin@myNode:~ $ cd /mnt/hdd/mynode/bitcoin/blocks
-bash: cd: /mnt/hdd/mynode/bitcoin/blocks: Permission denied
```

Also note, on my rig:

```
admin@myNode:~ $ groups
admin sudo docker bitcoin
```

The `admin` user in the `bitcoin` group is the only thing I've changed from the standard OEM `admin` user.

So clearly something is still not right here.

I think this is a feature that has to work.  Saving a user 3+ days, and 360 Gb of domestic download cap, is kind of a big deal.  All this is absolutely painless on Umbrel.

**Comment by tehelsper** [comment]
Hmm... looks like the files need 755 for admin to be able to scp the file for some reason. I updated the docs.

I've also got code to setup the folders that way, but I'm not sure if it means each new file will get readable permissions. I'll have to check as the data grows. If it works, the manual chmod would not be necessary.

**Comment by StevenBlack** [comment]
I'm going to close this now Taylor @tehelsper thank you for all your help.

In the end I did...

```bash
$ sudo chmod -R 755 /mnt/hdd/mynode/bitcoin
```

... so the `admin` user can prevail in the whole subtree, not just  in `blocks`, `chainstate`, and `indexes`.

All-good!  Cheers!

**Comment by tehelsper** [comment]
No problem! I didn't want to suggest the entire directory since that would make wallets with private keys or sensitive info more easily accessible, but it's not intended someone unauthorized could get that far anyway.

**Comment by StevenBlack** [comment]
Taylor @tehelsper that's a very good point. Thanks.
