### ISSUE TITLE
Settings page - Networking section has old UI view

### ISSUE THREAD

**Issue by tlindi** [mynodebtc/mynode_docs#50]
**Is your content request related to a problem? Please describe.**
Screenshot from UI is old at (https://github.com/mynodebtc/mynode_docs/tree/master/docs/networking)/tor.md

**Describe the solution you'd like**
Please update with latest version view.

**Additional context**
Please find updated view as attached:
![myNode-settings-Networkings](https://user-images.githubusercontent.com/7249767/202444219-ae899431-b7c2-429d-8af0-4c824ace505b.png)

**Comment by tehelsper** [comment]
Fixed. Thanks.
