### ISSUE TITLE
Tor setup on Linux section has incomplete sentence

### ISSUE THREAD

**Issue by dancuellar** [mynodebtc/mynode_docs#52]
**Description**
Under the Tor setup on Linux section of docs there is an incomplete sentence: "You may also want to install"

**Expected behavior**
Sentence finishes describing what else user may want installed. 

**Screenshots**
![Screenshot 2023-02-26 at 2 11 35 PM](https://user-images.githubusercontent.com/126418949/221434606-733aa4e0-ac99-4d62-8d62-e3972d7401c8.png)

**Desktop:**
 - OS: Mac OS X Ventura 13.2.1 (22D68)
 - Safari 16.3

**Comment by tehelsper** [comment]
Oh thanks, I'll fix. It was just going to say tor browser, but that's now in the section above it.

**Comment by tehelsper** [comment]
Fixed. Thanks!
