### ISSUE TITLE
BTCPay server

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode_docs#8]
**Is your content request related to a problem? Please describe.**
This is an app to receive Bitcoin/lightning payments, targeted to merchants and self-employed folks. Security must be taken care of while writing the instructions.

**Describe the solution you'd like**
- [ ] Overview
- [ ] Setup
- [ ] Testing and sample usage
- [ ] Troubleshooting

**Additional context**
MyNode is one of the few providers of BTCPayServer bundled with Bitcoin/Lightning node. Once implemented successfully, it could empower a huge number of merchants around the world.

**Comment by britttttk** [comment]
@abhiShandy someone is asking in the btcpay chat how to use the mynode lnd information to create a btcpay connection string for lnd. Do you have any example of this by chance? I can help you with this issue but I don't have access to a mynode..

**Comment by tehelsper** [comment]
IIRC, it should be pre-configured but required clicking a link like "use local node" when setting up lightning to populate the url for lnd access.
